### ISSUE TITLE
pathogen installation doesn't work

### ISSUE THREAD

**Issue by adrianstaniec** [ctjhoa/spacevim#13]
I can read the help, but no SPACE leader functionality works.
I installed all required plugins also with pathogen.
Can you help debug?

**Comment by ctjhoa** [comment]
I don't use pathogen so I haven't test it yet.
Do you see the `vim-leader-guide` ?

**Comment by adrianstaniec** [comment]
I don't see the guide appearing.
The space is just moving the cursor to the right.

Which plugin manager do you use?

Would you be so kind to maybe provide
a minimal .vimrc and .vim configuration for the spacevim to work?

**Comment by ctjhoa** [comment]
Yeah true. I'm working to improve installation and bootstrap a layer system. This evening, I've finally find a good way to do that. I'll keep you in touch.

Anyway personally I use [Shougo/neobundle.vim](https://github.com/Shougo/neobundle.vim) but I know that most of people use [junegunn/vim-plug](https://github.com/junegunn/vim-plug)

**Comment by ctjhoa** [comment]
With the new 2.0.0 the installation is really simplified in distribution mode

**Comment by adrianstaniec** [comment]
Wow! The installation now is a marvelous breeze ;]
Very nice work! Thank you
