### ISSUE TITLE
Adding additional plugins.

### ISSUE THREAD

**Issue by michalwarda** [ctjhoa/spacevim#19]
What should be the format for plugins inside `dotspacevim_additional_plugins`?

Trying to add `'vim-ruby/vim-ruby'` to the list throws an error of `Variable Type mismatch for: plugin`

**Comment by ctjhoa** [comment]
It should be something like:
`let g:dotspacevim_additional_plugins = ['vim-scripts/colorsupport.vim']`

Are you using distribution mode or key binding mode ?

**Comment by ctjhoa** [comment]
And what's your vim version?

**Comment by michalwarda** [comment]
```
" -*- mode: vimrc -*-
"vim: ft=vim

" spacevim automatic installation {{{
if empty(glob('~/.vim/autoload/spacevim.vim'))
    silent !curl -fLo ~/.vim/autoload/spacevim.vim --create-dirs
          \ https://raw.githubusercontent.com/ctjhoa/spacevim/master/autoload/spacevim.vim
endif
" }}}

let g:dotspacevim_distribution_mode = 1

let g:dotspacevim_configuration_layers = [
\  'core/.*',
\  'git',
\  'syntax-checking'
\]

let g:dotspacevim_additional_plugins = ['vim-scripts/colorsupport.vim']

let g:dotspacevim_excluded_plugins = []

" let g:dotspacevim_escape_key_sequence = 'fd'

let mapleader = ' '
let g:leaderGuide_vertical = 1
set dir=~/.tmp
set expandtab tabstop=2 shiftwidth=2
set nowrap 
set number
set relativenumber
set swapfile
set timeoutlen=1000 ttimeoutlen=10
set wildignore+=*/node_modules/*,*/bower_components/*,*.so,*.swp,*.zip

cnoreabbrev W w
cnoreabbrev Q q

" This must be the end of the file
call spacevim#bootstrap()
```

This is my whole dotfile.

My Vim version is 7.4.712

The error is:

```
Error detected while processing function spacevim#bootstrap:
line   98:
E706: Variable type mismatch for: plugin
```

**Comment by ctjhoa** [comment]
![2016-08-18-160006_1343x1731_scrot](https://cloud.githubusercontent.com/assets/1716173/17776447/e0ed44ca-655c-11e6-9682-37cc58c8f9a9.png)

I have no problem to load your vimrc. Try to run `:PlugInstall` to install additional packages

**Comment by ctjhoa** [comment]
Have you ever tried to install spacevim before? I know that `raw.githubusercontent.com` has a strong cache and sometimes you get an old version of spacevim.

You can check that comparing your `.vim/autoload/spacevim.vim` and the one in this repo.

**Comment by ctjhoa** [comment]
I've had better documentation in the `vimrc.sample`.

**Comment by michalwarda** [comment]
I've checked the vimrc on ubuntu and it works perfectly. On OS X though it's throwing the error.

**Comment by ctjhoa** [comment]
I have opened an new issue . I will close this one for clarity. Thanks
