### ISSUE TITLE
Add colorscheme

### ISSUE THREAD

**Issue by kmerz** [ctjhoa/spacevim#2]
Acutally I like the colorscheme alot from spacemacs and it seems you are pretty close with you vim colorscheme. So would be nice to have the resource.

**Comment by ctjhoa** [comment]
Hi, I don't use any colorscheme in vim. It's just my X11 colors which are customized.
You can find my X11 conf in my `dotfiles` repo :
https://github.com/ctjhoa/dotfiles/blob/master/X11/.config/colors/jasonwryan

Unfortunately, I don't know any spacemacs-dark colorcheme for vim.

Edit : My bad, you're right! I forgot that I've done a port of jasonwryan' s miro8:
https://github.com/ctjhoa/miro8

**Comment by ctjhoa** [comment]
Link added in the README

**Comment by kmerz** [comment]
Thanks alot!
