### ISSUE TITLE
improve plugins readme

### ISSUE THREAD

**Issue by WuTheFWasThat** [ctjhoa/spacevim#20]
first off, thanks for the 2.0.0 update to spacevim - it looks great!

I'm writing to nitpick about the PLUGINS.md presentation.  I don't know what the right answer is, but I'm just writing to inform you of some uncertainties I encountered.
- Are all plugins technically optional?  
- I'm not familiar with editorconfig-vim, but it seems unrelated to replicating spacemacs behavior, right?  
- vim-arpeggio also looks really cool, but what does it have to do with the git plugin?  
  I'm okay with my spacevim set up already, but a newcomer might have trouble deciding what plugins to add.

Maybe it also makes sense to sort by layer instead of by plugin - that way a user can easily decide, for example, to not include the git layer at all.  
It could also be really useful to have a brief description column, perhaps.

**Comment by ctjhoa** [comment]
> Are all plugins technically optional?

Yes

> I'm not familiar with editorconfig-vim, but it seems unrelated to replicating spacemacs behavior, right?

Yes I made a mistake as I use it all the time. I forgot that it needs to be add in addition-package in spacemacs

> vim-arpeggio also looks really cool, but what does it have to do with the git plugin?

You're also right, copy/paste mistake.

> Maybe it also makes sense to sort by layer instead of by plugin - that way a user can easily decide, for example, to not include the git layer at all.

Yeah. I'm think I'm gonna rework this.

**Comment by ctjhoa** [comment]
I've done some progress tell me what you think of that

**Comment by ctjhoa** [comment]
editorconfig is removed in dev branch

**Comment by WuTheFWasThat** [comment]
looks better!
