### ISSUE TITLE
Will it work with neovim too?

### ISSUE THREAD

**Issue by ghost** [ctjhoa/spacevim#33]
I included Plug 'ctjhoa/spacevim' to my init.vim for neovim. It doesn't seem to affect. Is this expected?

**Comment by ghost** [comment]
Sorry, it's working with neovim now. There was something wrong with my configuration probably. Closing this issue.

**Comment by ctjhoa** [comment]
Spacevim doesn't officialy support neovim as spacevim rely on many plugins and  I don't  use neovim but in theory it should work.
