### ISSUE TITLE
"SPC f f" results in error

### ISSUE THREAD

**Issue by Npahlfer** [ctjhoa/spacevim#34]
The keybinding _SPC f f_ throws error:
```
Error detected while processing function SpacevimFindFiles: line 2:
E499: Empty file name for '%' or '#', only works with ":p:h": Files %:h
```
I just added spacevim as a distribution.

**Comment by ctjhoa** [comment]
Which OS do you have ? Do you have install [fzf](https://github.com/junegunn/fzf#installation) ?

**Comment by Npahlfer** [comment]
Thx for a fast reply.
Im on OSX 10.11.6.
Yes, fzf is installed and I have restarted vim.

**Comment by ctjhoa** [comment]
OK I get it:
http://stackoverflow.com/questions/35135212/vim-source-command-results-in-error-e499

In short, `SPC f f` only work when file exist on the file system so it should not be a scratch file but an existing file.

**Comment by Npahlfer** [comment]
Ah, okey. Thanks for the help!
