### ISSUE TITLE
Make spacevim as a vim distribution?

### ISSUE THREAD

**Issue by wsdjeg** [ctjhoa/spacevim#35]
I have create a [SpaceVim](https://github.com/SpaceVim) github org, and SpaceVim/SpaceVim repo, and the init distribution was just split from my own config, and it support layer by default. 
what do you think make spacevim as a distribution instead of just a plugin?

**Comment by wsdjeg** [comment]
@ctjhoa BTW, ALL the code now is in dev branch, if all things done, I will merge it into master branch.

**Comment by ctjhoa** [comment]
@wsdjeg 
Sorry I don't have a lot of time to handle this project lately. I take a closer look at your vim distribution and I don't think we have the same goals.
Mine is to provide spacemacs shortcuts inside vim only because I was frustrated switching from emacs to vim.
Your project has a larger scope with different target (neovim) and define its own key bindings.

To conclude, I find your project too intrusive but it's great to see diversity.
Thanks anyway.

**Comment by wsdjeg** [comment]
@ctjhoa Thanks for your reply. but I think we have same goals. I have implement spacemacs like layer feature. as I said before, vim has different way to load files, `:source` command is not recommend, I use autoload feature. 
`:source` will effect the name space of vim's rtp. BTW, we should use autoload functions instead of global func just like `Layer()` or `UserInit()`, these functions maybe used by other plugins. But I think `SpaceVim#Layer()` will only be used by SpaceVim, It will be more safe!

now My main work is makking SpaceVim support leader guide. I will implement this feature in two ways:
1. Use unite menu show all the mappings and description. user can fuzzy find mapping by key sequence or description, and type `Enter` to execute this mapping.
2. Use vim-leader-guide, in this way, the guide will be open everytime when user type `Leader`. As I can say, I do not like this way, because most of the mapping the user can remember them, I do not think them need the guide everytime. I like the first way, the guide will not effect user's typping, but when user need, they can open the menu themself.

**Comment by ctjhoa** [comment]
@wsdjeg I think you're talking about [liuchengxu/space-vim](https://github.com/liuchengxu/space-vim).
I don't `source` any file and don't have any `Layer` or `UserInit` functions.

**Comment by wsdjeg** [comment]
@ctjhoa yeah, I am talking about space-vim, I have read the code of space-vim, but I do not like that type.

**Comment by autoferrit** [comment]
As a note, I actually prefer the keymapping layout as done here and in spacemacs. I tried using `SpaceVim` and the keys didnt always work for me (could have been my setup). But I still prefer command entry done on here.

**Comment by wsdjeg** [comment]
@autoferrit Thanks for have a try with SpaceVim, I also WANT to use the keymap layer, pr welcome.
