### ISSUE TITLE
Extra steps for additional plugins

### ISSUE THREAD

**Issue by eldamir** [ctjhoa/spacevim#37]
I used to setup YouCompleteMe through

`Plug 'Valloric/YouCompleteMe', {'do': './install.py'}`

How can I achieve this with the the `g:dotspacevim_additional_plugins` setting?

**Comment by ctjhoa** [comment]
Currently you can't. I need to do some changes in dev branch to support this.
If you don't want to wait you can:
- Use another spacevim https://github.com/liuchengxu/space-vim or https://github.com/SpaceVim/SpaceVim
- Do some work on dev branch to support this and make a PR :)

If I have time to work this weekend, I will try to add this feature in dev branch.
I'll keep you in touch.

**Comment by ctjhoa** [comment]
Finally, I fix this in master branch as there is no breaking change.
Take a look at the new [vimrc.sample](https://github.com/ctjhoa/spacevim/blob/master/vimrc.sample) for syntax. Don't hesitate to reopen this issue if something's wrong.

**Comment by eldamir** [comment]
Thank you for the quick action.
I'll give it a try soon.
