### ISSUE TITLE
Variable type mismatch in spacevim#bootstrap

### ISSUE THREAD

**Issue by leviroth** [ctjhoa/spacevim#39]
I installed a fresh version of Spacevim on Ubuntu 14.04 ("Trusty") using the "Distribution mode" shell line in the readme.

The following error messages are printed when starting vim:

```
Error detected while processing function spacevim#bootstrap:
line  103:
E706: Variable type mismatch for: additional_plugin
Error detected while processing /home/ubuntu/.vimrc:
line   63:
E185: Cannot find color scheme 'gruvbox'
Press ENTER or type command to continue
```

For convenience, here are the relevant lines of `spacevim.vim`, starting at line 103:

```
    if exists('g:dotspacevim_additional_plugins')
      for additional_plugin in g:dotspacevim_additional_plugins
        if type(additional_plugin) == type({})
          Plug additional_plugin.name, additional_plugin.option
        else
          Plug additional_plugin
        endif
      endfor
    endif
```

I take it the second error printed results from the failure to load gruvbox as an additional plugin.

[.vimrc included](https://github.com/ctjhoa/spacevim/files/722142/vimrc.txt)

**Comment by ctjhoa** [comment]
This must be linked to #37. I'll take a look ASAP.

**Comment by ctjhoa** [comment]
To sum up:
`E185: Cannot find color scheme 'gruvbox'`
It's because the `vimrc.sample` try to set the colorscheme to `gruvbox` which is not already installed at the first vim startup.

For the other error `E706: Variable type mismatch for: additional_plugin`, I cannot reproduce it. Can you show me the result of `$ vim --version`?

**Comment by ctjhoa** [comment]
PS: I have removed the installation of YouCompleteMe in the `vimrc.sample` tell me if you still got this error

**Comment by leviroth** [comment]
Installing the new version fixed it.

I've attached my `vim --version` output in case still useful.
[vversion.txt](https://github.com/ctjhoa/spacevim/files/733696/vversion.txt)

**Comment by leviroth** [comment]
> To sum up:
` E185: Cannot find color scheme 'gruvbox'`
> It's because the vimrc.sample try to set the colorscheme to gruvbox which is not already installed at the first vim startup.

I might have been unclear: This was happening even after restarting vim, likely because the line that initializes `g:dotspacevim_additional_plugins` was erroring, and thus the gruvbox plugin wasn't being loaded. But it seems to be a moot point.

(Accidentally closed this, but I take it it's resolved?)
