### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by ixodie** [ctjhoa/spacevim#43]
I got this:

Error detected while processing function SpaceVim#commands#install_plugin[4]..SpaceVim#plugins#manager#install[36]..<SNR>66_install[19]..12[43].
.<SNR>67_systemlist:
line    3:
E706: Variable type mismatch for: cmd

On OSX Sierra.

**Comment by ctjhoa** [comment]
what's your Vim version?

**Comment by ixodie** [comment]
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec  6 2016 12:07:41)
Included patches: 1-898, 8056
Compiled by root@apple.com

**Comment by ctjhoa** [comment]
@ixodie you're not on the right repo. Your error is related to [SpaceVim/SpaceVim](https://github.com/SpaceVim/SpaceVim).

There are 3 spacevim: [SpaceVim/SpaceVim](https://github.com/SpaceVim/SpaceVim), [liuchengxu/space-vim](https://github.com/liuchengxu/space-vim) and mine. All of them are independant from each other.
