### ISSUE TITLE
View update errors?

### ISSUE THREAD

**Issue by nedludd** [ctjhoa/spacevim#45]
Is there a way to see what caused a package to fail when you do `SPUdate`?

These guys:
<img width="477" alt="_usr_local_bin_vim__vim_" src="https://user-images.githubusercontent.com/17875/36504463-94afd328-171e-11e8-8f09-3262cba97e28.png">

**Comment by ctjhoa** [comment]
You are looking for this repo https://github.com/SpaceVim/SpaceVim not mine
